spring:
  datasource:
    url: jdbc:mariadb://naong-db.c8o7rl2nwppm.ap-northeast-2.rds.amazonaws.com:3306/naongdb
    username: admin
    password: criteria123!
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:

      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace