spring:
  datasource:
    url: jdbc:mariadb://naong-db.c8o7rl2nwppm.ap-northeast-2.rds.amazonaws.com:3306/naongdb
    username: admin
    password: criteria123!
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    credentials:
      access-key: AKIAVPJIFAHMH2RJTPEK
      secret-key: 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
    s3:
      bucket: naongbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false