spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  profiles:
    include: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  redis:
    host: localhost
    port: 6379
jwt:
  secret: bmV2ZXJtaW5kaWxsZmluZHNvbWVvbmVsaWtleW91aXdpc2g=
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace